# Generated by Django 3.1.2 on 2020-10-19 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Отчество')),
                ('deceased_surname', models.CharField(max_length=30, verbose_name='Фамилия усопшего')),
                ('deceased_name', models.CharField(max_length=30, verbose_name='Имя усопшего')),
                ('deceased_patronymic', models.CharField(max_length=30, verbose_name='Отчество усопшего')),
                ('phoneNumber', models.IntegerField(verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('hallID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('positionID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('salary', models.IntegerField(verbose_name='Зарпалата')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название товара')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductDiscounts',
            fields=[
                ('discountID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('discountAmount', models.IntegerField(verbose_name='Сумма скидки')),
            ],
            options={
                'verbose_name': 'Скидка на товары',
                'verbose_name_plural': 'Скидки на товары',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('productTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Тип товара')),
            ],
            options={
                'verbose_name': 'Тип товара',
                'verbose_name_plural': 'Типы товара',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('servicesID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('workerID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Отчество')),
                ('hallID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BD_Report.hall')),
                ('positionID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BD_Report.position')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('productOrderID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('sum', models.IntegerField(verbose_name='Сумма')),
                ('is_paid', models.BooleanField(verbose_name='Подтверждение оплаты')),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BD_Report.client')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BD_Report.product')),
            ],
            options={
                'verbose_name': 'Заказ товара',
                'verbose_name_plural': 'Заказы товара',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='discountID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BD_Report.productdiscounts'),
        ),
        migrations.AddField(
            model_name='product',
            name='productTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BD_Report.producttype'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('sum', models.IntegerField(verbose_name='Сумма')),
                ('is_paid', models.BooleanField(verbose_name='Подтверждение оплаты')),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BD_Report.client', verbose_name='Клиент')),
                ('discountID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BD_Report.services', verbose_name='Скидка')),
                ('hallID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BD_Report.hall', verbose_name='Зал')),
                ('workerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BD_Report.worker', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
            },
        ),
        migrations.AddField(
            model_name='hall',
            name='servicesID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BD_Report.services'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discountID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('discountAmount', models.IntegerField(verbose_name='Сумма скидки')),
                ('servicesID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BD_Report.services')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
    ]
