# Generated by Django 3.1.2 on 2020-10-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BD_Report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='sum',
        ),
    ]
