# Generated by Django 3.1.2 on 2020-10-22 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BD_Report', '0003_auto_20201022_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='servicesID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='BD_Report.services', verbose_name='Услуга'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='discountID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BD_Report.discount', verbose_name='Скидка'),
        ),
    ]
